article/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name  = 'article'

urlpatterns = [
    path('category/', login_required(views.NewsCategoryView.as_view()), name='category'),
    path('category-delete/<id>/', login_required(views.news_category_delete), name='news_category_delete'),
    
    path('add-article/', login_required(views.add_article), name='add_article'),
    path('article-list/', login_required(views.ArticleListView.as_view()), name='article_list'),
    path('article-delete/<id>/', login_required(views.article_delete), name='article_delete'),
    path('article-edit/<id>/', login_required(views.edit_article), name='edit_article'),
    
    path('breaking-news-add/', login_required(views.BreakingNewsCreateView.as_view()), name='breaking_news_add'),
    path('breaking-news-list/', login_required(views.BreakingNewsListView.as_view()), name='breaking_news_list'),
    path('breaking-news-edit/<pk>/', login_required(views.BreakingNewsUpdateView.as_view()), name='breaking_news_update'),
    path('breaking-news-delete/<int:id>/', login_required(views.breaking_news_delete), name='breaking_news_delete'),
    
    path('video-news-add/', login_required(views.add_videos_news), name='add_videos_news'),
    path('video-news-list/', login_required(views.VideoNewsListView.as_view()), name='video_news_list'),
    path('video-news-update/<id>/', login_required(views.edit_videos_news), name='edit_videos_news'),
    path('video-news-delete/<id>/', login_required(views.video_news_delete), name='video_news_delete'),
    
    path('epaper-add/', login_required(views.EpaperCreateView.as_view()), name='epaper_add'),
    path('epaper-list/', login_required(views.EpaperListView.as_view()), name='epaper_list'),
    path('epaper-edit/<pk>/', login_required(views.EpaperUpdateView.as_view()), name='epaper_update'),
    path('epaper-delete/<id>/', login_required(views.epaper_delete), name='epaper_delete'),
]

news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("article/", include("article.urls")),
    path("author/", include("author.urls")),
    path("content/", include("content.urls")),
    path("",  include("frontend.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# # urls.py
# from django.shortcuts import render

# def custom_page_not_found_view(request, exception):
#     return render(request, "frontend/404.html", {})

# handler404 = 'portfolio.urls.custom_page_not_found_view'

article/models.py
from django.db import models
from content.models import BaseModel
from django.utils.text import slugify
from django.urls import reverse
from unidecode import unidecode

def create_bengali_slug(bangla_text):
    # Transliterate Bengali to ASCII using unidecode
    transliterated_text = unidecode(bangla_text)
    # Use Django's slugify to create a slug from transliterated text
    slug = slugify(transliterated_text)
    return slug

class Category(BaseModel):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True, blank=True)
    

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'category'
        managed = True
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        
    def save(self, *args, **kwargs):
        if not self.slug:
            name = create_bengali_slug(self.name)
            self.slug = slugify(name)  # Automatically generate slug from title
        super().save(*args, **kwargs)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    def __str__(self):
        return self.name

    class Meta:
        db_table = 'tag'
        managed = True
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

class Article(BaseModel):
    title = models.CharField(max_length=100)
    author = models.ForeignKey('author.Author', on_delete=models.CASCADE, related_name='articles')
    content = models.TextField()
    date_published = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField('Category', related_name='articles')
    slug = models.SlugField(max_length=100, unique=True, blank=True)  # Allow blank slug for auto-generation
    tags = models.ManyToManyField('Tag', related_name='articles')
    image = models.ImageField(upload_to='article_image', blank=True, null=True)  # Optional image
    view_count = models.IntegerField(default=0)  # Optional view count through signals
    published_at = models.DateTimeField(null=True, blank=True)  # New field for actual publish time
    status = models.CharField(max_length=10, choices=[('draft', 'Draft'), ('published', 'Published')], default='draft')
    likes = models.IntegerField(default=0)  # New column for likes
    dislikes = models.IntegerField(default=0)  # New column for dislikes

    class Meta:
        db_table = 'article'
        managed = True
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'
        indexes = [
            models.Index(fields=['slug']),  # Add index for slug for faster lookups
        ]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            title =  create_bengali_slug(self.title)
            self.slug = slugify(title)  # Automatically generate slug from title
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('article_detail', kwargs={'slug': self.slug})  # Generate URL based on slug

class BreakingNews(BaseModel):
    title = models.CharField(max_length=255)
    description = models.TextField()
    status = models.CharField(max_length=10, choices=[('draft', 'Draft'), ('published', 'Published')], default='draft')
    
    def __str__(self):
        return self.title

    class Meta:
        db_table = 'breaking_news'
        managed = True
        verbose_name = 'Breaking News'
        verbose_name_plural = 'Breaking News' 

class Comment(BaseModel):
    article = models.ForeignKey('Article', on_delete=models.CASCADE, related_name='comments')
    name =  models.CharField(max_length=100,  blank=True, null=True)
    email = models.EmailField(max_length=100,  blank=True, null=True)
    content = models.TextField()
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')

    def __str__(self):
        return f'Comment by {self.reader.name} on {self.article.title}'  # Corrected

    class Meta:
        db_table = 'comment'
        managed = True
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

    @property
    def is_reply(self):
        """Return True if this comment is a reply to another comment."""
        return self.parent is not None

class Like(models.Model):
    article = models.ForeignKey('Article', on_delete=models.CASCADE, related_name='article_likes')
    author = models.ForeignKey('author.Author', on_delete=models.CASCADE, related_name='likes')
    date_liked = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Like by {self.author.name} on {self.article.title}'

    class Meta:
        db_table = 'like'
        managed = True
        verbose_name = 'Like'
        verbose_name_plural = 'Likes'
        unique_together = ('article', 'author')  # Prevent multiple likes by the same author on the same article
  
class VideoNews(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    video_url = models.URLField()  # Link to the video
    date_published = models.DateTimeField()
    categories = models.ManyToManyField('Category', related_name='video_news')
    thumbnail = models.ImageField(upload_to='video_thumbnails/', blank=True, null=True)  # Optional thumbnail field
    author = models.ForeignKey('author.Author', on_delete=models.CASCADE, related_name='videos_news')
    status = models.CharField(max_length=10, choices=[('draft', 'Draft'), ('published', 'Published')], default='draft')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'video_news'
        managed = True
        verbose_name = 'Video News'
        verbose_name_plural = 'Video News'

class Epaper(BaseModel):
    title = models.CharField(max_length=255)
    pdf_file = models.FileField(upload_to='epaper_pdf')
    date_published = models.DateField(blank=True,  null=True)
    page_number  = models.IntegerField(blank=True,  null=True)
    status = models.CharField(max_length=10, choices=[('draft', 'Draft'), ('published', 'Published')], default='draft')


    def __str__(self):
        return self.title

    class Meta:
        db_table = 'epaper'
        managed = True
        verbose_name = 'Epaper'
        verbose_name_plural = 'Epapers'

article/forms.py
from django import forms
from .models import Article, BreakingNews, Category, Epaper, Tag, VideoNews, Comment


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', )
        # Optional: You can customize the widget for the name field
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'id':'name',
                'class': 'form-control',
                'placeholder': 'Enter category name',
            }
        ),
        max_length=50
    )

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content', 'category', 'image', 'status']

    title = forms.CharField(
        widget=forms.TextInput(attrs={'id': 'title', 'class': 'form-control', 'placeholder': 'Enter article title'}),
        max_length=100
    )
    content = forms.CharField(
        widget=forms.Textarea(attrs={'id': 'content', 'class': 'form-control', 'placeholder': 'Enter article content'}),
    )
    category = forms.ModelMultipleChoiceField(
        queryset=Category.objects.none(),  # Set as none initially
        widget=forms.CheckboxSelectMultiple(attrs={'id': 'category'})
    )
    image = forms.ImageField(
        widget=forms.FileInput(attrs={'id': 'image', 'class': 'form-control'}),
        required=False
    )
    status = forms.ChoiceField(
        choices=[('draft', 'Draft'), ('published', 'Published')],
        widget=forms.RadioSelect(attrs={'id': 'status'})
    )

    def __init__(self, *args, **kwargs):
        author = kwargs.pop('author', None)  # Get the author from the kwargs
        super().__init__(*args, **kwargs)
        if author.is_superuser:
            self.fields['category'].queryset = Category.objects.all()  # If superuser, show
        elif author:
            self.fields['category'].queryset = author.category.all()  # Filter categories based on the author


class BreakingNewsForm(forms.ModelForm):
    class Meta:
        model = BreakingNews
        fields = ['title', 'description', 'status']
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'id':'title',
                'class': 'form-control',
                'placeholder': 'Enter breaking news title',
            }
        ),
        max_length=255
    )
    description = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'id':'description',
                'class': 'form-control',
                'placeholder': 'Enter breaking news description',
            }
        ),
    )
    status = forms.ChoiceField(
        choices=[('draft', 'Draft'), ('published', 'Published')],
        widget=forms.RadioSelect(attrs={'id': 'status'})
    )
    
class VideoNewsForm(forms.ModelForm):
    class Meta:
        model = VideoNews
        fields = ['title', 'description', 'video_url', 'categories', 'thumbnail', 'status', 'date_published']
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'id':'title',
                'class': 'form-control',
                'placeholder': 'Enter video news title',
            }
        ),
        max_length=255
    )
    description = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'id':'description',
                'class': 'form-control',
                'placeholder': 'Enter video news description',
            }
        ),
    )
    video_url = forms.URLField(
        widget=forms.URLInput(
            attrs={
                'id':'video_url',
                'class': 'form-control',
                'placeholder': 'Enter video URL',
            }
        ),
    )
    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'id': 'categories'})
    )
    thumbnail = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'id':'thumbnail',
                'class': 'form-control',
            }
        ),
        required=False
    )
    status = forms.ChoiceField(
        choices=[('draft', 'Draft'), ('published', 'Published')],
        widget=forms.RadioSelect(attrs={'id': 'status'})
    )
    date_published = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'id':'date_published',
                'class': 'form-control',
                'placeholder': 'YYYY-MM-DD',
                'type':'date'
            }
        ),
        required=False
    )


class EpaperForm(forms.ModelForm):
    class Meta:
        model = Epaper
        fields = ['title', 'pdf_file', 'date_published', 'page_number', 'status']
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'id':'title',
                'class': 'form-control',
                'placeholder': 'Enter epaper title',
            }
        ),
        max_length=255
    )
    pdf_file = forms.FileField(
        widget=forms.FileInput(
            attrs={
                'id':'pdf_file',
                'class': 'form-control',
            }
        ),
    )
    date_published = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'id':'date_published',
                'class': 'form-control',
                'placeholder': 'YYYY-MM-DD',
                'type':'date'
            }
        ),
        required=False
    )
    page_number = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={
                'id':'page_number',
                'class': 'form-control',
                'placeholder': 'Enter page number',
            }
        ),
        required=False
    )
    status = forms.ChoiceField(
        choices=[('draft', 'Draft'), ('published', 'Published')],
        widget=forms.RadioSelect(attrs={'id': 'status'})
    )
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'content', 'parent']  # Including 'name' and 'email' fields

        widgets = {
            'name': forms.TextInput(attrs={
                'id': 'comment-name',
                'class': 'form-control',
                'placeholder': 'আপনার নাম লিখুন (ঐচ্ছিক)',
            }),
            'email': forms.EmailInput(attrs={
                'id': 'comment-email',
                'class': 'form-control',
                'placeholder': 'আপনার ইমেল লিখুন (ঐচ্ছিক)',
            }),
            'content': forms.Textarea(attrs={
                'id': 'comment-content',
                'class': 'form-control',
                'placeholder': 'এখানে আপনার মন্তব্য লিখুন...',
                'rows': 4
            }),
            'parent': forms.HiddenInput(),  # Hidden field for handling replies
        }

templates/backend/article/article-edit.html
{% extends "backend/base.html" %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css" />
{% endblock head %}

{% block content %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} border-0 d-flex align-items-center" role="alert">
    <div class="bg-{{message.tags}} me-3 icon-item"><span class="fas fa-check-circle text-white fs-6"></span></div>
    <p class="mb-0 flex-1">{{message}}</p><button class="btn-close" type="button" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

<div class="card mb-3">
    <div class="card-header">
        <div class="row flex-between-end">
            <div class="col-auto align-self-center">
                <h5 class="mb-0" data-anchor="data-anchor" id="example">Edit Article</h5>
            </div>
        </div>
    </div>
    <div class="card-body bg-body-tertiary">
        <div class="tab-content">
            <div class="tab-pane preview-tab-pane active">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_title">Title:</label> 
                            {{ form.title }}
                        </div>
                        {% if user.is_superuser %}
                        <div class="col-md-6 mb-3">
                          <label for="id_title">Status:</label> 
                          <div class="d-flex" id="status">
                            {% for value, label in form.status.field.choices %}
                                <div class="form-check me-2">
                                    <input type="radio" id="{{ value }}" name="{{ form.status.name }}" value="{{ value }}" class="form-check-input" {% if form.status.value == value %}checked{% endif %}>
                                    <label for="{{ value }}" class="form-check-label">{{ label }}</label>
                                </div>
                            {% endfor %}
                        </div>
                        {% else %}
                        <div class="col-md-6 mb-3">
                          <label for="id_title">Status:</label> 
                          <div class="d-flex" id="status">
                            <div class="form-check me-2">
                                  <label for="status_0"><input type="radio" name="status" value="draft" id="status_0" required checked>
                                  Draft</label>
                              </div>
                        </div>
                        {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_image">Image:</label> 
                            {{ form.image }}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_tags">Tags:</label>
                            <select class="form-control select2" multiple="multiple" id="tags" name="tags">
                                {% for tag in tag_names %}
                                    <option value="{{ tag.name }}" {% if tag in article.tags.all %}selected{% endif %}>{{ tag.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="id_content">Content:</label> 
                            {{ form.content }}
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="id_category">Category:</label>
                            <div id="category" class="d-flex flex-wrap">
                                {% for category in form.category %}
                                    <div class="form-check me-3">
                                        {{ category.tag }}  <!-- Render the checkbox input -->
                                        <label for="{{ category.id_for_label }}" class="form-check-label">{{ category.choice_label }}</label>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.full.min.js"></script>

<script>
    $('.select2').select2({
        data: [],
        tags: true,
        maximumSelectionLength: 10,
        tokenSeparators: [',', ' '],
        placeholder: "Select or type keywords"
    });
</script>
{% endblock script %}

templates/backend/article/epaper-add.html
{% extends "backend/base.html" %}
{% load static %}

{% block content %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} border-0 d-flex align-items-center" role="alert">
    <div class="bg-{{message.tags}} me-3 icon-item"><span class="fas fa-check-circle text-white fs-6"></span></div>
    <p class="mb-0 flex-1">{{message}}</p><button class="btn-close" type="button" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
<div class="card mb-3">
    <div class="card-header">
      <div class="row flex-between-end">
        <div class="col-auto align-self-center">
          <h5 class="mb-0" data-anchor="data-anchor" id="example">Epaper Add</h5>
        </div>
        
      </div>
    </div>
    <div class="card-body bg-body-tertiary">
      <div class="tab-content">
        <div class="tab-pane preview-tab-pane active">
          <form method="post" enctype="multipart/form-data">

            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    <label for="id_title">Title:</label>
                    {{form.title}}
                </div>
                <div class="col-md-6">
                    <label for="id_pdf_file">Pdf File:</label>
                    {{form.pdf_file}}
                </div>
                <div class="col-md-6">
                    <label for="id_date_published">Date Published:</label>
                    {{form.date_published}}
                </div>
                <div class="col-md-6">
                    <label for="id_page_number">Page Number:</label>
                    {{form.page_number}}
                </div>
                <div class="col-md-6">
                    <label for="id_status">Status:</label>
                    {{form.status}}
                </div>
                <div class="col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/backend/article/epaper-edit.html
{% extends "backend/base.html" %}
{% load static %}

{% block content %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} border-0 d-flex align-items-center" role="alert">
    <div class="bg-{{message.tags}} me-3 icon-item"><span class="fas fa-check-circle text-white fs-6"></span></div>
    <p class="mb-0 flex-1">{{message}}</p><button class="btn-close" type="button" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
<div class="card mb-3">
    <div class="card-header">
      <div class="row flex-between-end">
        <div class="col-auto align-self-center">
          <h5 class="mb-0" data-anchor="data-anchor" id="example">Epaper Add</h5>
        </div>
        
      </div>
    </div>
    <div class="card-body bg-body-tertiary">
      <div class="tab-content">
        <div class="tab-pane preview-tab-pane active">
          <form method="post" enctype="multipart/form-data">

            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    <label for="id_title">Title:</label>
                    {{form.title}}
                </div>
                <div class="col-md-6">
                    <label for="id_pdf_file">Pdf File:</label>
                    {{form.pdf_file}}
                </div>
                <div class="col-md-6">
                    <label for="id_date_published">Date Published:</label>
                    {{form.date_published}}
                </div>
                <div class="col-md-6">
                    <label for="id_page_number">Page Number:</label>
                    {{form.page_number}}
                </div>
                <div class="col-md-6">
                    <label for="id_status">Status:</label>
                    {{form.status}}
                </div>
                <div class="col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/backend/article/video-news-add.html
{% extends "backend/base.html" %}
{% load static %}

{% block content %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} border-0 d-flex align-items-center" role="alert">
    <div class="bg-{{message.tags}} me-3 icon-item"><span class="fas fa-check-circle text-white fs-6"></span></div>
    <p class="mb-0 flex-1">{{message}}</p><button class="btn-close" type="button" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
<div class="card mb-3">
    <div class="card-header">
      <div class="row flex-between-end">
        <div class="col-auto align-self-center">
          <h5 class="mb-0" data-anchor="data-anchor" id="example">Breaking News Add</h5>
        </div>
        
      </div>
    </div>
    <div class="card-body bg-body-tertiary">
      <div class="tab-content">
        <div class="tab-pane preview-tab-pane active">
          <form method="post"  enctype="multipart/form-data">

            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    <label for="id_title">Title:</label>
                    {{form.title}}
                </div>
                <div class="col-md-6">
                    <label for="id_video_url">Video URL:</label>
                    {{form.video_url}}
                </div>

                <div class="col-md-6">
                    <label for="id_date_published">Date Published:</label>
                    {{form.date_published}}
                </div>

                <div class="col-md-6">
                    <label for="id_thumbnail">Thumbnail:</label>
                    {{form.thumbnail}}
                </div>

                <div class="col-md-6">
                    <label for="id_status">Status:</label>
                    {{form.status}}
                </div>
                <div class="col-md-12">
                    <label for="id_categories">Categories:</label>
                    <div id="categories" class="d-flex flex-wrap">
                        {% for category in form.categories %}
                            <div class="form-check me-3">
                                {{ category.tag }}  <!-- Render the checkbox input -->
                                <label for="{{ category.id_for_label }}" class="form-check-label">{{ category.choice_label }}</label>
                            </div>
                        {% endfor %}
                    </div>
                    
                </div>
                <div class="col-md-12">
                    <label for="id_description">Description:</label>
                    {{form.description}}
                </div>

                
                <div class="col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/backend/article/video-news-edit.html
{% extends "backend/base.html" %}
{% load static %}

{% block content %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} border-0 d-flex align-items-center" role="alert">
    <div class="bg-{{message.tags}} me-3 icon-item"><span class="fas fa-check-circle text-white fs-6"></span></div>
    <p class="mb-0 flex-1">{{message}}</p><button class="btn-close" type="button" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
<div class="card mb-3">
    <div class="card-header">
      <div class="row flex-between-end">
        <div class="col-auto align-self-center">
          <h5 class="mb-0" data-anchor="data-anchor" id="example">Breaking News Add</h5>
        </div>
        
      </div>
    </div>
    <div class="card-body bg-body-tertiary">
      <div class="tab-content">
        <div class="tab-pane preview-tab-pane active">
          <form method="post"  enctype="multipart/form-data">

            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    <label for="id_title">Title:</label>
                    {{form.title}}
                </div>
                <div class="col-md-6">
                    <label for="id_video_url">Video URL:</label>
                    {{form.video_url}}
                </div>

                <div class="col-md-6">
                    <label for="id_date_published">Date Published:</label>
                    {{form.date_published}}
                </div>

                <div class="col-md-6">
                    <label for="id_thumbnail">Thumbnail:</label>
                    {{form.thumbnail}}
                </div>

                <div class="col-md-6">
                    <label for="id_status">Status:</label>
                    {{form.status}}
                </div>
                <div class="col-md-12">
                    <label for="id_categories">Categories:</label>
                    <div id="categories" class="d-flex flex-wrap">
                        {% for category in form.categories %}
                            <div class="form-check me-3">
                                {{ category.tag }}  <!-- Render the checkbox input -->
                                <label for="{{ category.id_for_label }}" class="form-check-label">{{ category.choice_label }}</label>
                            </div>
                        {% endfor %}
                    </div>
                    
                </div>
                <div class="col-md-12">
                    <label for="id_description">Description:</label>
                    {{form.description}}
                </div>

                
                <div class="col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}