frontend/urls.py
from django.urls import path
from . import views
app_name = 'frontend'

urlpatterns = [
    path('',views.index,  name='index'),
    path('world-news/', views.world_news, name='world_news'),
    path('politics-news/', views.politics_news, name='politics_news'),
    path('sports-news/', views.sports_news, name='sports_news'),
    path('bangladesh-news/', views.bangladesh_news, name='bangladesh_news'),
    path('crime-news/', views.crime_news, name='crime_news'),
    path('entertainment-news/', views.entertainment_news, name='entertainment_news'),
    path('business-news/', views.business_news, name='business_news'),
    path('opinion-news/', views.opinion_news, name='opinion_news'),
    path('job-news/', views.job_news, name='job_news'),
    path('lifestyle-news/', views.lifestyle_news, name='lifestyle_news'),
    
    
    path('news/<slug:slug>/', views.news_details, name='news_details'),
    
    path('news-tag/<int:id>/<tag>/', views.news_list_tags, name='news_list_tags'),
    


]

news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("article/", include("article.urls")),
    path("author/", include("author.urls")),
    path("content/", include("content.urls")),
    path("",  include("frontend.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# # urls.py
# from django.shortcuts import render

# def custom_page_not_found_view(request, exception):
#     return render(request, "frontend/404.html", {})

# handler404 = 'portfolio.urls.custom_page_not_found_view'

frontend/models.py
from django.db import models

# Create your models here.

frontend/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib import messages
from article.models import  Article, BreakingNews, Category, Comment, Tag
from django.utils import timezone
from datetime import timedelta
from content.models import PhotoGallery, VideoGallery
import re
from article.forms import CommentForm
from author.models import Author
from author.forms import AuthorForm


def extract_youtube_id(url):
    """
    Extract YouTube video ID from a URL.
    Supports formats like:
    - https://www.youtube.com/watch?v=ID
    - https://youtu.be/ID
    """
    youtube_regex = (
        r'(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{11})'
    )
    match = re.match(youtube_regex, url)
    if match:
        return match.group(1)
    return None

def index(request):
    context =  {}


    # Get the current time
    now = timezone.now()
    time_threshold = now - timedelta(hours=360)
    

    context['breaking_news_list'] = BreakingNews.objects.filter(status="published", created_at__gte=time_threshold).order_by('-created_at')[:2]
    context['latest_news_list'] = Article.objects.filter(status="published", created_at__gte=time_threshold).order_by('-created_at')[:8]
    context['world_news_list'] = Article.objects.filter(category__name="বিশ্ব" ,status="published", created_at__gte=time_threshold).order_by('-created_at')[:4]
    context['national_news_list'] = Article.objects.filter(category__name="বাংলাদেশ" ,status="published", created_at__gte=time_threshold).order_by('-created_at')[:4]
    
    populer_time_threshold = now - timedelta(hours=480)
    context['popular_news_list'] = Article.objects.filter(status="published", created_at__gte=populer_time_threshold).order_by('-view_count')
    context['sports_news_list'] = Article.objects.filter(category__name="খেলা" ,status="published", created_at__gte=time_threshold).order_by('-created_at')[:5]
    context['opinion_list'] = Article.objects.filter(category__name="মতামত" ,status="published", created_at__gte=time_threshold).order_by('-created_at')
    context['photo_gallery_list'] = PhotoGallery.objects.filter(created_at__gte=time_threshold).order_by('-created_at')
    context['entertainment_list'] = Article.objects.filter(category__name="বিনোদন" ,status="published", created_at__gte=time_threshold).order_by('-created_at')[:3]
    video_list= VideoGallery.objects.filter(created_at__gte=time_threshold).order_by('-created_at')[:2]
        # Modify video_list to include only the YouTube video ID
    videos_with_ids = []
    for video in video_list:
        video_id = extract_youtube_id(video.video_url)
        videos_with_ids.append({
            'title': video.title,
            'video_id': video_id
        })
    context['video_list'] = videos_with_ids
    
    
    
    context['business_list'] = Article.objects.filter(category__name="বাণিজ্য" ,status="published", created_at__gte=time_threshold).order_by('-created_at')
    
    
    context['categories']  = Category.objects.all()
    context['tags'] =  Tag.objects.all()

    context['page_title'] = "জনপদ সংবাদ | সত্যের সন্ধানে, প্রতিদিন"
    context['page_name'] = 'index'
    context['page_color'] = 'red'
    return render(request, 'frontend/index.html', context)


def world_news(request):
    context = {}
    now = timezone.now()
    time_threshold = now - timedelta(hours=360)
    context['latest_news_list'] = Article.objects.filter(category__name="বিশ্ব", status="published", created_at__gte=time_threshold).order_by('-created_at')[:8]
    context['world_news_list'] = Article.objects.filter(category__name="বিশ্ব" ,status="published", created_at__gte=time_threshold).order_by('-created_at')
    context['popular_news_list'] = Article.objects.filter(category__name="বিশ্ব" ,status="published", created_at__gte=time_threshold).order_by('-view_count')
    
    context['categories']  = Category.objects.all()
    context['tags'] =  Tag.objects.all()
    context['page_title'] = "বিশ্ব | জনপদ সংবাদ | সত্যের সন্ধানে, প্রতিদিন"
    context['page_name'] = 'world_news'
    context['page_color'] = 'orange'
    return render(request, 'frontend/world_news.html', context)


def politics_news(request):
    context = {}
    now = timezone.now()
    time_threshold = now - timedelta(hours=360)
    context['latest_news_list'] = Article.objects.filter(category__name="রাজনীতি", status="published", created_at__gte=time_threshold).order_by('-created_at')[:8]
    context['politics_news_list'] = Article.objects.filter(category__name="রাজনীতি" ,status="published", created_at__gte=time_threshold).order_by('-created_at')
    context['popular_news_list'] = Article.objects.filter(category__name="রাজনীতি" ,status="published", created_at__gte=time_threshold).order_by('-view_count')
    
    context['categories']  = Category.objects.all()
    context['tags'] =  Tag.objects.all()
    context['page_title'] = "রাজনীতি | জনপদ সংবাদ | সত্যের সন্ধানে, প্রতিদিন"
    context['page_name'] = 'politics_news'
    context['page_color'] = 'blue'
    return render(request, 'frontend/politics_news.html', context)

def sports_news(request):
    context = {}
    now = timezone.now()
    time_threshold = now - timedelta(hours=360)
    context['latest_news_list'] = Article.objects.filter(category__name="খেলা", status="published", created_at__gte=time_threshold).order_by('-created_at')[:8]
    context['sports_news_list'] = Article.objects.filter(category__name="খেলা" ,status="published", created_at__gte=time_threshold).order_by('-created_at')
    context['popular_news_list'] = Article.objects.filter(category__name="খেলা" ,status="published", created_at__gte=time_threshold).order_by('-view_count')
    
    context['categories']  = Category.objects.all()
    context['tags'] =  Tag.objects.all()
    context['page_title'] = "খেলা | জনপদ সংবাদ | সত্যের সন্ধানে, প্রতিদিন"
    context['page_name'] = 'sports_news'
    context['page_color'] = 'green'

    return render(request, 'frontend/sports_news.html', context)

def bangladesh_news(request):
    context = {}
    now = timezone.now()
    time_threshold = now - timedelta(hours=360)
    context['latest_news_list'] = Article.objects.filter(category__name="বাংলাদেশ", status="published", created_at__gte=time_threshold).order_by('-created_at')[:8]
    context['bangladesh_news_list'] = Article.objects.filter(category__name="বাংলাদেশ" ,status="published", created_at__gte=time_threshold).order_by('-created_at')
    context['popular_news_list'] = Article.objects.filter(category__name="বাংলাদেশ" ,status="published", created_at__gte=time_threshold).order_by('-view_count')
    
    context['categories']  = Category.objects.all()
    context['tags'] =  Tag.objects.all()
    context['page_title'] = "বাংলাদেশ | জনপদ সংবাদ | সত্যের সন্ধানে, প্রতিদিন"
    context['page_name'] = 'bangladesh_news'
    context['page_color'] = 'deep-orange'

    return render(request, 'frontend/bangladesh_news.html', context)

def crime_news(request):
    context = {}
    now = timezone.now()
    time_threshold = now - timedelta(hours=360)
    context['latest_news_list'] = Article.objects.filter(category__name="অপরাধ", status="published", created_at__gte=time_threshold).order_by('-created_at')[:8]
    context['crime_news_list'] = Article.objects.filter(category__name="অপরাধ" ,status="published", created_at__gte=time_threshold).order_by('-created_at')
    context['popular_news_list'] = Article.objects.filter(category__name="অপরাধ" ,status="published", created_at__gte=time_threshold).order_by('-view_count')
    
    context['categories']  = Category.objects.all()
    context['tags'] =  Tag.objects.all()
    context['page_title'] = "অপরাধ | জনপদ সংবাদ | সত্যের সন্ধানে, প্রতিদিন"
    context['page_name'] = 'crime_news'
    context['page_color'] = 'purple'

    return render(request, 'frontend/crime_news.html', context)

def entertainment_news(request):
    context = {}
    now = timezone.now()
    time_threshold = now - timedelta(hours=360)
    context['latest_news_list'] = Article.objects.filter(category__name="বিনোদন", status="published", created_at__gte=time_threshold).order_by('-created_at')[:8]
    context['entertainment_news_list'] = Article.objects.filter(category__name="বিনোদন" ,status="published", created_at__gte=time_threshold).order_by('-created_at')
    context['popular_news_list'] = Article.objects.filter(category__name="বিনোদন" ,status="published", created_at__gte=time_threshold).order_by('-view_count')
    
    context['categories']  = Category.objects.all()
    context['tags'] =  Tag.objects.all()
    context['page_title'] = "বিনোদন | জনপদ সংবাদ | সত্যের সন্ধানে, প্রতিদিন"
    context['page_name'] = 'entertainment_news'
    context['page_color'] = 'slate'

    return render(request, 'frontend/entertainment_news.html', context)

def business_news(request):
    context = {}
    now = timezone.now()
    time_threshold = now - timedelta(hours=360)
    context['latest_news_list'] = Article.objects.filter(category__name="বাণিজ্য", status="published", created_at__gte=time_threshold).order_by('-created_at')[:8]
    context['business_news_list'] = Article.objects.filter(category__name="বাণিজ্য" ,status="published", created_at__gte=time_threshold).order_by('-created_at')
    context['popular_news_list'] = Article.objects.filter(category__name="বাণিজ্য" ,status="published", created_at__gte=time_threshold).order_by('-view_count')
    
    context['categories']  = Category.objects.all()
    context['tags'] =  Tag.objects.all()
    context['page_title'] = "বাণিজ্য | জনপদ সংবাদ | সত্যের সন্ধানে, প্রতিদিন"
    context['page_name'] = 'business_news'
    context['page_color'] = 'turquoise'

    return render(request, 'frontend/business_news.html', context)

def opinion_news(request):
    context = {}
    now = timezone.now()
    time_threshold = now - timedelta(hours=360)

templates/frontend/includes/copyright.html
{% load static %}
<div id="copyrights"> 
    <!-- Begin .container -->
    <div class="container"> 
      <!-- Begin .copyright -->
      <div class="copyright"> &copy; 2016, Copyrights 24hNews Theme. All Rights Reserved </div>
      <!-- End .copyright --> 
      <!--  Begin .footer-social-icons -->
      <div class="footer-social-icons">
        <ul>
          <li> <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a> </li>
          <li> <a href="#" class="facebook"><i class="fa fa-facebook"></i></a> </li>
          <li> <a href="#" class="twitter"><i class="fa fa-twitter"></i></a> </li>
          <li> <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a> </li>
        </ul>
      </div>
      <!--  End .footer-social-icons --> 
    </div>
    <!-- End .container --> 
  </div>

templates/frontend/includes/footer.html
{% load static %}
<footer id="footer"> 
    <!-- Begin .parallax -->
    <div id="parallax-section2">
      <div class="bg parallax2 overlay img-overlay2">
        <div class="container">
          <div class="row no-gutter">
            <div class="col-sm-6 col-md-3">
              <h3 class="title-left title-style03 underline03">আমাদের সম্পর্কে</h3>
              <p class="about-us">আমাদের সম্পর্কে" বিভাগটি আপনার সংবাদপত্র বা ওয়েবসাইটের পরিচিতি দেয়ার জন্য অত্যন্ত গুরুত্বপূর্ণ। এটি পাঠকদের কাছে আপনার প্রতিষ্ঠান, উদ্দেশ্য এবং সেবার বিষয়ে স্বচ্ছ ধারণা প্রদান করে।<br>
                "আমাদের সম্পর্কে" বিভাগ পাঠকদের আপনার লক্ষ্য এবং মূল্যবোধ সম্পর্কে ধারণা দেবে এবং তাদের আপনার সংবাদপত্রের প্রতি আস্থা তৈরি করবে।</p>
              <div class="site-logo"><a href="index-2.html"><img src="{% static 'frontend/img/logo.png' %}" alt="Side Logo" />
                <h3>জনপদ <span>সংবাদ</span></h3>
                <p>সত্যের সন্ধানে, প্রতিদিন</p>
                </a></div>
            </div>
            <div class="col-sm-6 col-md-3">
              <h3 class="title-left title-style03 underline03">খবর</h3>
              <div class="footer-post">
                <ul>
                  {% for latest_news in latest_news_list|slice:":4" %}
                  <li>
                    <div class="item">
                      <div class="item-image"><a class="img-link" href="deals.html">
                        {% if latest_news.image %}
                        <img class="img-responsive img-full" src="{{latest_news.image.url}}" alt=""></a>
                        {% endif %}
                      </div>
                      <div class="item-content">
                        <p class="ellipsis"><a href="#">{{latest_news.title}}</a></p>
                      </div>
                    </div>
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
            <div class="col-sm-6 col-md-3">
              <h3 class="title-left title-style03 underline03">দেখুন + শুনুন</h3>
              <div class="footer-post">
                <ul>
                  {% for video in video_list %}
                  <li>
                    <div class="item">
                      <div class="item-image">
                  <iframe src="https://www.youtube.com/embed/{{video.video_id}}" class="video" title="{{video.title}}"></iframe>
                        
                      </div>
                      <div class="item-content">
                        <p class="ellipsis"><a href="#">{{video.title}}</a></p>
                      </div>
                    </div>
                  </li>
                  {% endfor %}


                </ul>
              </div>
            </div>
            <div class="col-sm-6 col-md-3">
              <h3 class="title-left title-style03 underline03">ট্যাগ</h3>
              <div class="tagcloud">
                {% for tag in tags %}
                <a href="#">{{tag.name}}</a>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- End .parallax --> 
  </footer>

templates/frontend/includes/header.html
{% load static %}
<header id="header"> 
    <!-- Begin .top-menu -->
    <div class="top-menu"> 
      <!-- Begin .container -->
      <div class="container"> 
        <!-- Begin .left-top-menu -->
        <ul class="left-top-menu">
          <li> <a href="#" class="facebook"><i class="fa fa-facebook"></i></a></li>
          <li> <a href="#" class="twitter"><i class="fa fa-twitter"></i></a> </li>
          <li> <a href="#" class="youtube"> <i class="fa fa-youtube"></i></a> </li>
          <li> <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a> </li>
          <li> <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a> </li>
          <li> <a href="#" class="instagram"> <i class="fa fa-instagram"></i></a> </li>
          <li class="address"><a href="#"><i class="fa fa-phone"></i> +00 (123) 456 7890</a></li>
          <li class="address"><a href="#"><i class="fa fa-envelope-o"></i> info@domain.com</a></li>
        </ul>
        <!-- End .left-top-menu --> 
        <!-- Begin .right-top-menu -->
        <ul class="right-top-menu pull-right">
          <li class="contact"><a href="contact.html"><i class="fa fa-map-marker fa-i"></i></a></li>
          <li class="about"><a href="about-us.html"><i class="fa fa-user fa-i"></i></a> </li>
          <li>
            <div class="search-container">
              <div class="search-icon-btn"> <span style="cursor:pointer"><i class="fa fa-search"></i></span> </div>
              <div class="search-input">
                <input type="search" class="search-bar" placeholder="Search..." title="Search"/>
              </div>
            </div>
          </li>
        </ul>
        <!-- End .right-top-menu --> 
      </div>
      <!-- End .container --> 
    </div>
    <!-- End .top-menu --> 
    <!-- Begin .container -->
    <div class="container"> 
      <!-- Begin .header-logo -->
      <div class="header-logo"><a href="{% url "frontend:index" %}"><img src="{% static 'frontend/img/logo.png' %}" alt="Site Logo" />
        <h1>জনপদ <span>সংবাদ</span></h1>
        <h4>সত্যের সন্ধানে, প্রতিদিন</h4>
        </a></div>
      <!-- End .header-logo --> 
      <!-- Begin .header-add-place -->
      <div class="header-add-place">

        <div class="desktop-add"><a href="https://themeforest.net/item/24h-news-broadcast-news-tv-channel-news-magazine-template/18614179" target="_blank"><img src="{% static 'frontend/img/banner_728x90.jpg' %}" alt=""></a></div>
      </div>
      <!-- End .header-add-place --> 
      <!--========== BEGIN .NAVBAR #MOBILE-NAV ==========-->
      <nav class="navbar navbar-default" id="mobile-nav">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" id="sidenav-toggle"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <div class="sidenav-header-logo"><a href="index-2.html"><img src="{% static 'frontend/img/logo.png' %}" alt="Site Logo" />
            <h2>জনপদ <span>সংবাদ</span></h2>
            <h5>সত্যের সন্ধানে, প্রতিদিন</h5>
            </a></div>

        </div>
        <div class="sidenav" data-sidenav data-sidenav-toggle="#sidenav-toggle">
          <button type="button" class="navbar-toggle active" data-toggle="collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <div class="sidenav-brand">
            <div class="sidenav-header-logo"><a href="index-2.html"><img src="{% static 'frontend/img/logo.png' %}" alt="Site Logo" />
              <h2>জনপদ  <span>সংবাদ</span></h2>
              <h5>সত্যের সন্ধানে, প্রতিদিন</h5>
              </a></div>

          </div>
          <ul class="sidenav-menu">
            <li><a href="index-2.html" class="active">সর্বশেষ</a>
            </li>
            <li><a href="{% url "frontend:world_news" %}">বিশ্ব</a>
            </li>
            <li><a href="{% url "frontend:politics_news" %}">রাজনীতি</a>
            </li>
            <li><a href="{% url "frontend:sports_news" %}">খেলা</a>
            </li>
            <li><a href="{% url "frontend:bangladesh_news" %}">বাংলাদেশ</a>
            </li>
            <li><a href="{% url "frontend:crime_news" %}">অপরাধ</a>
            </li>
            <li><a href="{% url "frontend:entertainment_news" %}">বিনোদন</a>
            </li>
            <li><a href="{% url "frontend:business_news" %}">বাণিজ্য</a></li>
            <li><a href="{% url "frontend:opinion_news" %}">মতামত</a></li>
            <li><a href="{% url "frontend:job_news" %}">চাকরি</a></li>
            <li><a href="{% url "frontend:lifestyle_news" %}">জীবনযাপন</a></li>

          </ul>
        </div>
      </nav>
      <!--========== END .NAVBAR #MOBILE-NAV ==========--> 
    </div>
    <!-- End .container --> 
    <!--========== BEGIN .NAVBAR #FIXED-NAVBAR ==========-->
    <div class="navbar" id="fixed-navbar"> 
      <!--========== BEGIN MAIN-MENU .NAVBAR-COLLAPSE COLLAPSE #FIXED-NAVBAR-TOOGLE ==========-->
      <div class="main-menu nav navbar-collapse collapse" id="fixed-navbar-toggle"> 
        <!--========== BEGIN .CONTAINER ==========-->
        <div class="container"> 
          <!-- Begin .nav navbar-nav -->
          <ul class="nav navbar-nav">
            <li class=" {% if page_name == 'index' %} active  {% endif %} "><a href="{% url "frontend:index" %}">সর্বশেষ</a></li>
            <li class=" {% if page_name == 'world_news' %} active  {% endif %} " ><a href="{% url "frontend:world_news" %}">বিশ্ব</a> </li>
            <li class=" {% if page_name == 'politics_news' %} active  {% endif %} " ><a href="{% url "frontend:politics_news" %}">রাজনীতি</a> </li>
            <li class=" {% if page_name == 'sports_news' %} active  {% endif %} " ><a href="{% url "frontend:sports_news" %}">খেলা</a></li>
            <li class=" {% if page_name == 'bangladesh_news' %} active  {% endif %} " ><a href="{% url "frontend:bangladesh_news" %}">বাংলাদেশ</a></li>
            <li class=" {% if page_name == 'crime_news' %} active  {% endif %} " ><a href="{% url "frontend:crime_news" %}">অপরাধ</a></li>
            <li class=" {% if page_name == 'entertainment_news' %} active  {% endif %} " ><a href="{% url "frontend:entertainment_news" %}">বিনোদন</a></li>
            <li class=" {% if page_name == 'business_news' %} active  {% endif %} " ><a href="{% url "frontend:business_news" %}">বাণিজ্য</a></li>
            <li class=" {% if page_name == 'opinion_news' %} active  {% endif %} " ><a href="{% url "frontend:opinion_news" %}">মতামত</a></li>
            <li class=" {% if page_name == 'job_news' %} active  {% endif %} " ><a href="{% url "frontend:job_news" %}">চাকরি</a></li>
            <li class=" {% if page_name == 'lifestyle_news' %} active  {% endif %} " ><a href="{% url "frontend:lifestyle_news" %}">জীবনযাপন</a></li>

          </ul>
          <!--========== END .NAV NAVBAR-NAV ==========--> 
        </div>
        <!--========== END .CONTAINER ==========--> 
      </div>
      <!--========== END MAIN-MENU .NAVBAR-COLLAPSE COLLAPSE #FIXED-NAVBAR-TOOGLE ==========--> 
      <!--========== BEGIN .SECOND-MENU NAVBAR #NAV-BELOW-MAIN ==========-->
      <div class="second-menu navbar" id="nav-below-main"> 
        <!-- Begin .container -->
        <div class="container"> 
          <!-- Begin .collapse navbar-collapse -->
          <div class="collapse navbar-collapse nav-below-main"> 
            <!-- Begin .nav navbar-nav -->

          </div>
          <!-- End .collapse navbar-collapse --> 
          <!-- Begin .clock -->
          <div class="clock">
            <div id="time"></div>
            <div id="date"></div>
          </div>
          <!-- End .clock --> 
        </div>
        <!-- End .container --> 
      </div>
      <!--========== END .SECOND-MENU NAVBAR #NAV-BELOW-MAIN ==========--> 
    </div>
  </header>