article/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name  = 'article'

urlpatterns = [
    path('category/', login_required(views.NewsCategoryView.as_view()), name='category'),
    path('category-delete/<id>/', login_required(views.news_category_delete), name='news_category_delete'),
    
    path('add-article/', login_required(views.add_article), name='add_article'),
    path('article-list/', login_required(views.ArticleListView.as_view()), name='article_list'),
    path('article-delete/<id>/', login_required(views.article_delete), name='article_delete'),
    path('article-edit/<id>/', login_required(views.edit_article), name='edit_article'),
    
    path('breaking-news-add/', login_required(views.BreakingNewsCreateView.as_view()), name='breaking_news_add'),
    path('breaking-news-list/', login_required(views.BreakingNewsListView.as_view()), name='breaking_news_list'),
    path('breaking-news-edit/<pk>/', login_required(views.BreakingNewsUpdateView.as_view()), name='breaking_news_update'),
    path('breaking-news-delete/<int:id>/', login_required(views.breaking_news_delete), name='breaking_news_delete'),
    
    path('video-news-add/', login_required(views.add_videos_news), name='add_videos_news'),
    path('video-news-list/', login_required(views.VideoNewsListView.as_view()), name='video_news_list'),
    path('video-news-update/<id>/', login_required(views.edit_videos_news), name='edit_videos_news'),
    path('video-news-delete/<id>/', login_required(views.video_news_delete), name='video_news_delete'),
    
    path('epaper-add/', login_required(views.EpaperCreateView.as_view()), name='epaper_add'),
    path('epaper-list/', login_required(views.EpaperListView.as_view()), name='epaper_list'),
    path('epaper-edit/<pk>/', login_required(views.EpaperUpdateView.as_view()), name='epaper_update'),
    path('epaper-delete/<id>/', login_required(views.epaper_delete), name='epaper_delete'),
]

author/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views
app_name = 'author'

urlpatterns = [
    path('author-add/', login_required(views.author_add), name='author_add'),
    path('author-list/', login_required(views.AuthorListView.as_view()), name='author_list'),
    path('author-edit/<id>/', login_required(views.author_edit), name='author_edit'),
    path('author-delete/<id>/', login_required(views.author_delete), name='author_delete'),
    
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.author_profile, name='author_profile'),

    
]

content/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views
app_name = 'content'
urlpatterns = [
    path('', login_required(views.index), name='index'),
    
    path('photo-gallery/', login_required(views.PhotoGelleryViews.as_view()), name='photo_gallery'),
    path('photo-delete/<id>/', login_required(views.photo_gallery_delete), name='photo_gallery_delete'),
    
    path('video-gallery/', login_required(views.VideoGelleryViews.as_view()), name='video_gallery'),
    path('video-delete/<id>/', login_required(views.video_gallery_delete), name='video_gallery_delete'),
    
    path("pages/", views.CommonPagesViews.as_view(), name="pages"),
    path("shortcut/", views.ShortcutViews.as_view(), name="shortcut")
    
]

news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("article/", include("article.urls")),
    path("author/", include("author.urls")),
    path("content/", include("content.urls")),
    path("",  include("frontend.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# # urls.py
# from django.shortcuts import render

# def custom_page_not_found_view(request, exception):
#     return render(request, "frontend/404.html", {})

# handler404 = 'portfolio.urls.custom_page_not_found_view'

templates/backend/includes/footer.html
{% load static %}
<footer class="footer">
    <div class="row g-0 justify-content-between fs-10 mt-4 mb-3">
      <div class="col-12 col-sm-auto text-center">
        <p class="mb-0 text-600">Thank you for creating with Wahid <span class="d-none d-sm-inline-block">| </span><br class="d-sm-none" /> 2024 &copy; <a href="ss">Wahid</a></p>
      </div>
      <div class="col-12 col-sm-auto text-center">
        <p class="mb-0 text-600">v3.21.0</p>
      </div>
    </div>
  </footer>

templates/backend/includes/header.html
{% load static %}
<nav class="navbar navbar-light navbar-glass navbar-top navbar-expand-lg" style="display: none;">
    <button class="btn navbar-toggler-humburger-icon navbar-toggler me-1 me-sm-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarStandard" aria-controls="navbarStandard" aria-expanded="false" aria-label="Toggle Navigation"><span class="navbar-toggle-icon"><span class="toggle-line"></span></span></button>
    <a class="navbar-brand me-1 me-sm-3" href="index.html">
      <div class="d-flex align-items-center"><img class="me-2" src="{% static 'backend/assets/img/icons/spot-illustrations/falcon.png' %}" alt="" width="40" /><span class="font-sans-serif text-primary">falcon</span></div>
    </a>


  </nav>

templates/backend/includes/second-header.html
{% load static %}
<nav class="navbar navbar-light navbar-glass navbar-top navbar-expand-lg" style="display: none;" data-move-target="#navbarVerticalNav" data-navbar-top="combo">
    <button class="btn navbar-toggler-humburger-icon navbar-toggler me-1 me-sm-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarVerticalCollapse" aria-controls="navbarVerticalCollapse" aria-expanded="false" aria-label="Toggle Navigation"><span class="navbar-toggle-icon"><span class="toggle-line"></span></span></button>
    <a class="navbar-brand me-1 me-sm-3" href="index.html">
      <div class="d-flex align-items-center"><img class="me-2" src="{% static 'backend/assets/img/icons/spot-illustrations/falcon.png' %}" alt="" width="40" /><span class="font-sans-serif text-primary">falcon</span></div>
    </a>
    <div class="collapse navbar-collapse scrollbar" id="navbarStandard">
      <ul class="navbar-nav" data-top-nav-dropdowns="data-top-nav-dropdowns">

      </ul>
    </div>
    <ul class="navbar-nav navbar-nav-icons ms-auto flex-row align-items-center">
      <li class="nav-item ps-2 pe-0">
        <div class="dropdown theme-control-dropdown"><a class="nav-link d-flex align-items-center dropdown-toggle fa-icon-wait fs-9 pe-1 py-0" href="#" role="button" id="themeSwitchDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fas fa-sun fs-7" data-fa-transform="shrink-2" data-theme-dropdown-toggle-icon="light"></span><span class="fas fa-moon fs-7" data-fa-transform="shrink-3" data-theme-dropdown-toggle-icon="dark"></span><span class="fas fa-adjust fs-7" data-fa-transform="shrink-2" data-theme-dropdown-toggle-icon="auto"></span></a>
          <div class="dropdown-menu dropdown-menu-end dropdown-caret border py-0 mt-3" aria-labelledby="themeSwitchDropdown">
            <div class="bg-white dark__bg-1000 rounded-2 py-2"><button class="dropdown-item d-flex align-items-center gap-2" type="button" value="light" data-theme-control="theme"><span class="fas fa-sun"></span>Light<span class="fas fa-check dropdown-check-icon ms-auto text-600"></span></button><button class="dropdown-item d-flex align-items-center gap-2" type="button" value="dark" data-theme-control="theme"><span class="fas fa-moon" data-fa-transform=""></span>Dark<span class="fas fa-check dropdown-check-icon ms-auto text-600"></span></button><button class="dropdown-item d-flex align-items-center gap-2" type="button" value="auto" data-theme-control="theme"><span class="fas fa-adjust" data-fa-transform=""></span>Auto<span class="fas fa-check dropdown-check-icon ms-auto text-600"></span></button></div>
          </div>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link notification-indicator notification-indicator-primary px-0 fa-icon-wait" id="navbarDropdownNotification" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-hide-on-body-scroll="data-hide-on-body-scroll"><span class="fas fa-bell" data-fa-transform="shrink-6" style="font-size: 33px;"></span></a>
        <div class="dropdown-menu dropdown-caret dropdown-caret dropdown-menu-end dropdown-menu-card dropdown-menu-notification dropdown-caret-bg" aria-labelledby="navbarDropdownNotification">
          <div class="card card-notification shadow-none">
            <div class="card-header">
              <div class="row justify-content-between align-items-center">
                <div class="col-auto">
                  <h6 class="card-header-title mb-0">Notifications</h6>
                </div>
                <div class="col-auto ps-0 ps-sm-3"><a class="card-link fw-normal" href="#">Mark all as read</a></div>
              </div>
            </div>
            <div class="scrollbar-overlay" style="max-height:19rem">
              <div class="list-group list-group-flush fw-normal fs-10">
                <div class="list-group-title border-bottom">NEW</div>
                <div class="list-group-item">
                  <a class="notification notification-flush notification-unread" href="#!">
                    <div class="notification-avatar">
                      <div class="avatar avatar-2xl me-3">
                        <img class="rounded-circle" src="{% static 'backend/assets/img/team/1-thumb.png' %}" alt="" />
                      </div>
                    </div>
                    <div class="notification-body">
                      <p class="mb-1"><strong>Emma Watson</strong> replied to your comment : "Hello world 😍"</p>
                      <span class="notification-time"><span class="me-2" role="img" aria-label="Emoji">💬</span>Just now</span>
                    </div>
                  </a>
                </div>
                <div class="list-group-item">
                  <a class="notification notification-flush notification-unread" href="#!">
                    <div class="notification-avatar">
                      <div class="avatar avatar-2xl me-3">
                        <div class="avatar-name rounded-circle"><span>AB</span></div>
                      </div>
                    </div>
                    <div class="notification-body">
                      <p class="mb-1"><strong>Albert Brooks</strong> reacted to <strong>Mia Khalifa's</strong> status</p>
                      <span class="notification-time"><span class="me-2 fab fa-gratipay text-danger"></span>9hr</span>
                    </div>
                  </a>
                </div>
                <div class="list-group-title border-bottom">EARLIER</div>
                <div class="list-group-item">
                  <a class="notification notification-flush" href="#!">
                    <div class="notification-avatar">
                      <div class="avatar avatar-2xl me-3">
                        <img class="rounded-circle" src="{% static 'backend/assets/img/icons/weather-sm.jpg' %}" alt="" />
                      </div>
                    </div>
                    <div class="notification-body">
                      <p class="mb-1">The forecast today shows a low of 20&#8451; in California. See today's weather.</p>
                      <span class="notification-time"><span class="me-2" role="img" aria-label="Emoji">🌤️</span>1d</span>
                    </div>
                  </a>
                </div>
                <div class="list-group-item">
                  <a class="border-bottom-0 notification-unread  notification notification-flush" href="#!">
                    <div class="notification-avatar">
                      <div class="avatar avatar-xl me-3">
                        <img class="rounded-circle" src="{% static 'backend/assets/img/logos/oxford.png' %}" alt="" />
                      </div>
                    </div>
                    <div class="notification-body">
                      <p class="mb-1"><strong>University of Oxford</strong> created an event : "Causal Inference Hilary 2019"</p>
                      <span class="notification-time"><span class="me-2" role="img" aria-label="Emoji">✌️</span>1w</span>
                    </div>
                  </a>
                </div>
                <div class="list-group-item">
                  <a class="border-bottom-0 notification notification-flush" href="#!">
                    <div class="notification-avatar">
                      <div class="avatar avatar-xl me-3">
                        <img class="rounded-circle" src="{% static 'backend/assets/img/team/10.jpg' %}" alt="" />
                      </div>
                    </div>
                    <div class="notification-body">
                      <p class="mb-1"><strong>James Cameron</strong> invited to join the group: United Nations International Children's Fund</p>
                      <span class="notification-time"><span class="me-2" role="img" aria-label="Emoji">🙋‍</span>2d</span>
                    </div>
                  </a>
                </div>
              </div>
            </div>
            <div class="card-footer text-center border-top"><a class="card-link d-block" href="app/social/notifications.html">View all</a></div>
          </div>
        </div>
      </li>

      <li class="nav-item dropdown"><a class="nav-link pe-0 ps-2" id="navbarDropdownUser" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <div class="avatar avatar-xl">
            <img class="rounded-circle" src="{% static 'backend/assets/img/team/3-thumb.png' %}" alt="" />
          </div>
        </a>
        <div class="dropdown-menu dropdown-caret dropdown-caret dropdown-menu-end py-0" aria-labelledby="navbarDropdownUser">
          <div class="bg-white dark__bg-1000 rounded-2 py-2">
            <a class="dropdown-item fw-bold text-warning" href="#!"></span><span>{{user.name}}</span></a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url "author:author_profile" %}">Profile &amp; account</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url "author:logout" %}">Logout</a>
          </div>
        </div>
      </li>
    </ul>
  </nav>

  <script>
    var navbarPosition = localStorage.getItem('navbarPosition');
    var navbarVertical = document.querySelector('.navbar-vertical');
    var navbarTopVertical = document.querySelector('.content .navbar-top');
    var navbarTop = document.querySelector('[data-layout] .navbar-top:not([data-double-top-nav');
    var navbarDoubleTop = document.querySelector('[data-double-top-nav]');
    var navbarTopCombo = document.querySelector('.content [data-navbar-top="combo"]');

    if (localStorage.getItem('navbarPosition') === 'double-top') {
      document.documentElement.classList.toggle('double-top-nav-layout');
    }

    if (navbarPosition === 'top') {
      navbarTop.removeAttribute('style');
      navbarTopVertical.remove(navbarTopVertical);
      navbarVertical.remove(navbarVertical);
      navbarTopCombo.remove(navbarTopCombo);
      navbarDoubleTop.remove(navbarDoubleTop);
    } else if (navbarPosition === 'combo') {
      navbarVertical.removeAttribute('style');
      navbarTopCombo.removeAttribute('style');
      navbarTop.remove(navbarTop);
      navbarTopVertical.remove(navbarTopVertical);
      navbarDoubleTop.remove(navbarDoubleTop);
    } else if (navbarPosition === 'double-top') {
      navbarDoubleTop.removeAttribute('style');
      navbarTopVertical.remove(navbarTopVertical);
      navbarVertical.remove(navbarVertical);
      navbarTop.remove(navbarTop);
      navbarTopCombo.remove(navbarTopCombo);
    } else {
      navbarVertical.removeAttribute('style');
      navbarTopVertical.removeAttribute('style');
      navbarTop.remove(navbarTop);
      navbarDoubleTop.remove(navbarDoubleTop);
      navbarTopCombo.remove(navbarTopCombo);
    }
  </script>

templates/backend/includes/sidebar.html
{% load static %}
<nav class="navbar navbar-light navbar-vertical navbar-expand-xl" id="navbar" style="display: none;">
    <script>
      document.addEventListener("DOMContentLoaded", function () {
        var navbarStyle = localStorage.getItem("navbarStyle") || 'light';  // Default to 'light' if not found
        if (navbarStyle !== 'transparent') {
          document.querySelector('.navbar-vertical').classList.add(`navbar-${navbarStyle}`);
        }
        document.getElementById('navbar').style.display = 'block';  // Show navbar after script runs
      });
    </script>
    <div class="d-flex align-items-center">
      <div class="toggle-icon-wrapper">
        <button class="btn navbar-toggler-humburger-icon navbar-vertical-toggle" data-bs-toggle="tooltip" data-bs-placement="left" title="Toggle Navigation">
          <span class="navbar-toggle-icon"><span class="toggle-line"></span></span>
        </button>
      </div>
      <a class="navbar-brand" href="index.html">
        <div class="d-flex align-items-center py-3">
          <img class="me-2" src="{% static 'backend/assets/img/icons/spot-illustrations/falcon.png' %}" alt="" width="40" />
          <span class="font-sans-serif text-primary">ADMIN</span>
        </div>
      </a>
    </div>
    <div class="collapse navbar-collapse" id="navbarVerticalCollapse">
      <div class="navbar-vertical-content scrollbar">
        <ul class="navbar-nav flex-column mb-3" id="navbarVerticalNav">

          <li class="nav-item"><!-- label-->
            <div class="row navbar-vertical-label-wrapper mt-3 mb-2">
              <div class="col-auto navbar-vertical-label">ARTICLE</div>
              <div class="col ps-0">
                <hr class="mb-0 navbar-vertical-divider" />
              </div>
            </div>
            <a class="nav-link" href="#" role="button">
              <div class="d-flex align-items-center">
                <span class="nav-link-icon"><span class="fas fa-chart-pie"></span></span>
                <span class="nav-link-text ps-1">Dashboard</span>
              </div>
            </a>
            {% if user.is_superuser %}
            <a class="nav-link" href="{% url "article:category" %}" role="button">
              <div class="d-flex align-items-center">
                <span class="nav-link-icon"><span class="fas fa-layer-group"></span></span>
                <span class="nav-link-text ps-1">News Category</span>
              </div>
            </a>
            {% endif %}
          </li>

          <li class="nav-item"><!-- parent pages-->
            <a class="nav-link dropdown-indicator collapsed" href="#articleManage" role="button" data-bs-toggle="collapse" aria-expanded="flase" aria-controls="articleManage">
              <div class="d-flex align-items-center">
                <span class="nav-link-icon"><span class="fas fa-chart-pie"></span></span>
                <span class="nav-link-text ps-1">Article Manage</span>
              </div>
            </a>
            <ul class="nav collapse" id="articleManage">
              <li class="nav-item">
                <a class="nav-link" href="{% url "article:add_article" %}">
                  <div class="d-flex align-items-center">
                    <span class="nav-link-text ps-1">Add Article</span>
                  </div>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "article:article_list" %}">
                  <div class="d-flex align-items-center">
                    <span class="nav-link-text ps-1">Article List</span>
                  </div>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item"><!-- parent pages-->
            <a class="nav-link dropdown-indicator collapsed" href="#breakinNewsManage" role="button" data-bs-toggle="collapse" aria-expanded="false" aria-controls="breakinNewsManage">
              <div class="d-flex align-items-center">
                <span class="nav-link-icon"><span class="fas fa-chart-pie"></span></span>
                <span class="nav-link-text ps-1">Breaking News Manage</span>
              </div>
            </a>
            <ul class="nav collapse" id="breakinNewsManage">
              <li class="nav-item">
                <a class="nav-link" href="{% url "article:breaking_news_add" %}">
                  <div class="d-flex align-items-center">
                    <span class="nav-link-text ps-1">Add Breaking News</span>
                  </div>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "article:breaking_news_list" %}">
                  <div class="d-flex align-items-center">
                    <span class="nav-link-text ps-1">Breaking News List</span>
                  </div>
                </a>
              </li>
            </ul>
          </li>


          <li class="nav-item"><!-- parent pages-->
            <a class="nav-link dropdown-indicator collapsed" href="#videoNewsManage" role="button" data-bs-toggle="collapse" aria-expanded="false" aria-controls="videoNewsManage">
              <div class="d-flex align-items-center">
                <span class="nav-link-icon"><span class="fas fa-chart-pie"></span></span>
                <span class="nav-link-text ps-1">Video News Manage</span>
              </div>
            </a>
            <ul class="nav collapse" id="videoNewsManage">
              <li class="nav-item">
                <a class="nav-link" href="{% url "article:add_videos_news" %}">
                  <div class="d-flex align-items-center">
                    <span class="nav-link-text ps-1">Add Video News</span>
                  </div>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "article:video_news_list" %}">
                  <div class="d-flex align-items-center">
                    <span class="nav-link-text ps-1">Video News List</span>
                  </div>
                </a>
              </li>
            </ul>
          </li>
          {% if user.is_superuser %}
          <li class="nav-item"><!-- parent pages-->
            <a class="nav-link dropdown-indicator collapsed" href="#epaperManage" role="button" data-bs-toggle="collapse" aria-expanded="false" aria-controls="epaperManage">
              <div class="d-flex align-items-center">
                <span class="nav-link-icon"><span class="fas fa-chart-pie"></span></span>
                <span class="nav-link-text ps-1">Epaper Manage</span>
              </div>
            </a>
            <ul class="nav collapse" id="epaperManage">
              <li class="nav-item">
                <a class="nav-link" href="{% url "article:epaper_add" %}">
                  <div class="d-flex align-items-center">
                    <span class="nav-link-text ps-1">Add Epaper</span>
                  </div>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "article:epaper_list" %}">
                  <div class="d-flex align-items-center">
                    <span class="nav-link-text ps-1">Epaper List</span>
                  </div>
                </a>
              </li>
            </ul>
          </li>
          
          <li class="nav-item"><!-- parent pages-->
            <a class="nav-link dropdown-indicator collapsed" href="#authorManage" role="button" data-bs-toggle="collapse" aria-expanded="false" aria-controls="authorManage">
              <div class="d-flex align-items-center">
                <span class="nav-link-icon"><span class="fas fa-chart-pie"></span></span>
                <span class="nav-link-text ps-1">Auhtor Manage</span>
              </div>
            </a>
            <ul class="nav collapse" id="authorManage">
              <li class="nav-item">
                <a class="nav-link" href="{% url "author:author_add" %}">
                  <div class="d-flex align-items-center">
                    <span class="nav-link-text ps-1">Add Author</span>
                  </div>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "author:author_list" %}">
                  <div class="d-flex align-items-center">
                    <span class="nav-link-text ps-1">Author List</span>
                  </div>
                </a>
              </li>
            </ul>
          </li>
          {% endif %}

          {% if user.is_superuser %}
          <a class="nav-link" href="{% url "content:photo_gallery" %}" role="button">
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><span class="fas fa-chart-pie"></span></span>
              <span class="nav-link-text ps-1">Photo Gallery</span>
            </div>
          </a>
          <a class="nav-link" href="{% url "content:video_gallery" %}" role="button">
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><span class="fas fa-chart-pie"></span></span>
              <span class="nav-link-text ps-1">Video Gallery</span>
            </div>
          </a>

          <a class="nav-link" href="{% url "content:pages" %}" role="button">
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><span class="fas fa-chart-pie"></span></span>
              <span class="nav-link-text ps-1">Pages</span>
            </div>
          </a>

          <a class="nav-link" href="{% url "content:shortcut" %}" role="button">
            <div class="d-flex align-items-center">
              <span class="nav-link-icon"><span class="fas fa-chart-pie"></span></span>
              <span class="nav-link-text ps-1">Shortcut</span>
            </div>
          </a>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>